// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/home/rjmonna/src/reactnative/node_modules/react');
var { Component } = React;
var ReactNative = require('/home/rjmonna/src/reactnative/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('reactnative', appParameters);
});
require('/home/rjmonna/src/reactnative/index.js');